/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-variant': '#2d3449',
        'primary-container': '#00a74b',
        'on-surface': '#dae2fd',
        'surface-bright': '#31394d',
        'surface': '#000000',
        'background': '#000000',
        'secondary-container': '#1ca64d',
        'on-tertiary': '#660027',
        'surface-container-lowest': '#000000',
        'on-secondary': '#003914',
        'surface-tint': '#4ae176',
        'surface-container-highest': '#2d3449',
        'on-surface-variant': '#bdcaba',
        'on-background': '#dae2fd',
        'outline-variant': '#3e4a3d',
        'surface-container': '#171f33',
        'outline': '#879485',
        'on-primary': '#003915',
        'on-primary-container': '#003111',
        'primary-fixed': '#6bff8f',
        'surface-container-high': '#222a3d',
        'surface-container-low': '#131b2e',
        'tertiary': '#ffb2bf',
        'tertiary-container': '#ec6284',
        'secondary': '#62df7d',
        'primary': '#4ae176',
        'inverse-primary': '#006e2f',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
